name: Sync GitHub Issue to Jira

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: zippie-labs.atlassian.net
          PROJECT_KEY: VEN
        run: |
          curl -D- -u $JIRA_USER:$JIRA_API_TOKEN \
          -X POST \
          -H "Content-Type: application/json" \
          --data '{
            "fields": {
              "project": { "key": "'"$PROJECT_KEY"'" },
              "summary": "'"${{ github.event.issue.title }}"'",
              "description": "'"${{ github.event.issue.body }}"'",
              "issuetype": { "name": "Bug" },
              "labels": [
                "github"
              ],
              "parent": {
                "key": "VEN-175"
              }
            }
          }' https://$JIRA_DOMAIN/rest/api/3/issue
